In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_json("D:\\Programming\\data\\Tourist recommendation\\\\final.json")

In [4]:
data.head()

,reviewTags,ancestorLocations,nearestMetroStations,subcategories,subtype,rankingString,name,latitude,ratingHistogram,numberOfReviews,...,locationString,rating,type,rankingPosition,category,localName,id,description,rawRanking,rankingDenominator
0,[],"[{'id': '304551', 'name': 'New Delhi', 'abbrev...","[{'name': 'Mayur Vihar -I', 'localName': 'Mayu...",[Tours],"[Multi-day Tours, Cultural Tours, Private Tour...","#59 of 2,134 Tours in New Delhi",Keeper Landwey,28.600508,"{'count1': 27, 'count2': 29, 'count3': 58, 'co...",10055,...,"New Delhi, National Capital Territory of Delhi",5.0,ATTRACTION,59,attraction,Keeper Landwey,12946789,Keeper Landwey is a Destination Management Com...,4.433018,2134
1,[],"[{'id': '635747', 'name': 'Baga', 'abbreviatio...",[],"[Zoos & Aquariums, Water & Amusement Parks, Fu...","[Theme Parks, Aquariums, Game & Entertainment ...",#1 of 2 Fun & Games in Baga,Goosebumps Virtual Escape,15.555789,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",82,...,"Baga, North Goa District, Goa",5.0,ATTRACTION,1,attraction,Goosebumps Virtual Escape,25073480,Goosebumps- virtual escape Let's walk into vir...,4.418244,2
2,[],"[{'id': '297668', 'name': 'Jodhpur', 'abbrevia...",[],[Sights & Landmarks],"[Ancient Ruins, Architectural Buildings]",#1 of 103 things to do in Jodhpur,Walk to blueCity heritagetour,26.297567,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",112,...,"Jodhpur, Jodhpur District, Rajasthan",5.0,ATTRACTION,1,attraction,Walk to blueCity heritagetour,15694922,Blue City heritage tour is walk to blueCity ar...,4.416904,103
3,[],"[{'id': '297633', 'name': 'Kochi (Cochin)', 'a...",[],[Transportation],[Taxis & Shuttles],#1 of 220 Transportation in Kochi (Cochin),J & J Taxi Service,9.970154,"{'count1': 4, 'count2': 2, 'count3': 6, 'count...",1426,...,"Kochi (Cochin), Ernakulam District, Kerala",5.0,ATTRACTION,1,attraction,J & J Taxi Service,13155645,"Welcome To J&J Taxi Service, we are one of the...",4.483928,220
4,[],"[{'id': '304554', 'name': 'Mumbai', 'abbreviat...",[],[Spas & Wellness],"[Yoga & Pilates, Hammams & Turkish Baths, Spas]",#2 of 226 Spas & Wellness in Mumbai,Muktaa The Wellness Clinic & Luxury Spa Marine...,18.930307,"{'count1': 4, 'count2': 2, 'count3': 2, 'count...",1031,...,"Mumbai, Maharashtra",5.0,ATTRACTION,2,attraction,Muktaa The Wellness Clinic & Luxury Spa Marine...,13174371,"The name Muktaa comes from the Indian origin, ...",4.502504,226

In [5]:
data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
reviewTags,1008,235,[],774,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ancestorLocations,1008,311,"[{'id': '304551', 'name': 'New Delhi', 'abbrev...",134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nearestMetroStations,1008,76,[],930,NaN,NaN,NaN,NaN,NaN,NaN,NaN
subcategories,1008,72,[Sights & Landmarks],255,NaN,NaN,NaN,NaN,NaN,NaN,NaN
subtype,1008,474,[Sacred & Religious Sites],125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rankingString,1008,1008,"#59 of 2,134 Tours in New Delhi",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,1008,1000,Dolphin's Nose,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,842.0,NaN,NaN,NaN,21.898438,6.835833,8.07801,15.508664,24.252063,27.156481,34.167664
ratingHistogram,1008,989,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
numberOfReviews,1008.0,NaN,NaN,NaN,552.547619,1551.783608,1.0,110.0,227.5,532.0,32199.0
longitude,842.0,NaN,NaN,NaN,76.970016,4.067233,68.95338,73.983749,76.617105,78.003926,93.79613
locationString,1008,311,"New Delhi, National Capital Territory of Delhi",134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rating,1008.0,NaN,NaN,NaN,4.634425,0.418105,3.0,4.5,4.5,5.0,5.0
type,1008,1,ATTRACTION,1008,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rankingPosition,1008.0,NaN,NaN,NaN,13.761905,27.270262,1.0,2.0,4.0,12.0,294.0
category,1008,1,attraction,1008,NaN,NaN,NaN,NaN,NaN,NaN,NaN
localName,1008,1000,Dolphin's Nose,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id,1008.0,NaN,NaN,NaN,8968650.21627,7081974.444692,311613.0,3220364.0,7185237.5,13433280.75,26874669.0
description,527,527,Keeper Landwey is a Destination Management Com...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rawRanking,1008.0,NaN,NaN,NaN,3.931252,0.56729,2.748375,3.388967,4.139601,4.418244,5.0
rankingDenominator,1008.0,NaN,NaN,NaN,367.295635,589.814841,1.0,24.0,71.0,441.0,2449.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewTags            1008 non-null   object
 1   ancestorLocations     1008 non-null   object
 2   nearestMetroStations  1008 non-null   object
 3   subcategories         1008 non-null   object
 4   subtype               1008 non-null   object
 5   rankingString         1008 non-null   object
 6   name                  1008 non-null   object
 7   latitude              842 non-null    float64
 8   ratingHistogram       1008 non-null   object
 9   numberOfReviews       1008 non-null   int64
 10  longitude             842 non-null    float64
 11  locationString        1008 non-null   object
 12  rating                1008 non-null   float64
 13  type                  1008 non-null   object
 14  rankingPosition       1008 non-null   int64
 15  category              1008 non-null   object
 16  localName             1008 non-null   object
 17  id                    1008 non-null   int64
 18  description           527 non-null    object
 19  rawRanking            1008 non-null   float64
 20  rankingDenominator    1008 non-null   int64
dtypes: float64(4), int64(4), object(13)
memory usage: 165.5+ KB

In [7]:
data.columns

Index(['reviewTags', 'ancestorLocations', 'nearestMetroStations',
       'subcategories', 'subtype', 'rankingString', 'name', 'latitude',
       'ratingHistogram', 'numberOfReviews', 'longitude', 'locationString',
       'rating', 'type', 'rankingPosition', 'category', 'localName', 'id',
       'description', 'rawRanking', 'rankingDenominator'],
      dtype='object')

In [8]:
for i in data.columns:
    if data[i].isnull().sum():
        print(f"{i}  :  { data[i].isnull().sum()}")

latitude  :  166
longitude  :  166
description  :  481

In [9]:
data.shape

(1008, 21)

In [10]:
data.isnull().sum()

reviewTags                0
ancestorLocations         0
nearestMetroStations      0
subcategories             0
subtype                   0
rankingString             0
name                      0
latitude                166
ratingHistogram           0
numberOfReviews           0
longitude               166
locationString            0
rating                    0
type                      0
rankingPosition           0
category                  0
localName                 0
id                        0
description             481
rawRanking                0
rankingDenominator        0
dtype: int64

In [11]:
data['type'].unique()

array(['ATTRACTION'], dtype=object)

In [12]:
data["subtype"]

0       [Multi-day Tours, Cultural Tours, Private Tour...
1       [Theme Parks, Aquariums, Game & Entertainment ...
2                [Ancient Ruins, Architectural Buildings]
3                                      [Taxis & Shuttles]
4         [Yoga & Pilates, Hammams & Turkish Baths, Spas]
                              ...
1003                           [Sacred & Religious Sites]
1004                                         [Waterfalls]
1005                                     [Shopping Malls]
1006                                         [Waterfalls]
1007                           [Sacred & Religious Sites]
Name: subtype, Length: 1008, dtype: object

In [13]:
data["subtype"].explode().unique()

array(['Multi-day Tours', 'Cultural Tours', 'Private Tours', 'Bus Tours',
       'Day Trips', 'Theme Parks', 'Aquariums',
       'Game & Entertainment Centers', 'Ancient Ruins',
       'Architectural Buildings', 'Taxis & Shuttles', 'Yoga & Pilates',
       'Hammams & Turkish Baths', 'Spas', 'Gift & Specialty Shops',
       'Sacred & Religious Sites', 'Nature & Wildlife Areas',
       'Points of Interest & Landmarks', 'Monuments & Statues',
       'Art Galleries', 'Castles', 'Observation Decks & Towers',
       'Historic Sites', 'Historical & Heritage Tours', 'Rail Tours',
       'Gardens', 'Shopping Malls', 'Art Museums', 'City Tours',
       'Cooking Classes', 'Walking Tours', 'Food Tours',
       'Health/Fitness Clubs & Gyms', 'Sightseeing Tours',
       'Motorcycle Tours', 'Hiking & Camping Tours', 'Factory Outlets',
       'Safaris', 'Bus Transportation', 'Lessons & Workshops',
       'Antique Stores', 'Hop-On Hop-Off Tours', 'Wine Tours & Tastings ',
       'Self-Guided Tours & Rentals', 'Bike Tours', 'Eco Tours',
       'Boat Rentals', 'Nature & Wildlife Tours', 'Archaeology Tours',
       'Sports Camps & Clinics', 'Shopping Tours', 'Boat Tours',
       'Water Sports', 'Kayaking & Canoeing', 'River Rafting & Tubing',
       'Adrenaline & Extreme Tours', 'Night Tours', 'Concerts',
       'Movie & TV Tours', '4WD, ATV & Off-Road Tours',
       'Photography Tours', 'Factory Tours', 'Climbing Tours',
       'Hiking Trails', 'Paint & Pottery Studios',
       'Zipline & Aerial Adventure Parks', 'Scuba & Snorkeling',
       'Shark Diving', 'Stand-Up Paddleboarding', 'Speed Boats Tours',
       'Parasailing & Paragliding', 'Vespa, Scooter & Moped Tours',
       'Ski & Snow Tours', 'Gear Rentals', 'Gondola Cruises',
       'Horseback Riding Tours', 'Balloon Rides', 'Running Tours',
       'Bar, Club & Pub Tours', 'Dolphin & Whale Watching',
       'Fishing Charters & Tours', 'Canyoning & Rappelling Tours',
       'Biking Trails', 'Dams', 'Bodies of Water', 'Zoos', 'Parks',
       'Beaches', 'Waterfalls', 'Deserts', 'Caverns & Caves',
       'National Parks', 'History Museums', 'Mountains', 'Valleys',
       'Specialty Museums', 'Scenic Drives', 'Neighborhoods',
       'Geologic Formations', 'Lookouts', 'Ski & Snowboard Areas',
       'Forests', 'Arenas & Stadiums', 'Islands', 'Lighthouses',
       'Hot Springs & Geysers', 'Cultural Events',
       'Flea & Street Markets', 'Bridges', 'Mass Transportation Systems',
       'Tramways', 'Casinos', 'Churches & Cathedrals', 'Scenic Railroads',
       'Cemeteries', 'Farms', 'Science Museums',
       'Observatories & Planetariums', 'Water Parks', 'Libraries',
       'Military Museums', 'Historic Walking Areas', 'Theaters',
       'Educational sites', 'Playgrounds', 'Department Stores',
       'Wineries & Vineyards'], dtype=object)

In [14]:
if "Sacred & Religious Sites" in data["subtype"]:
    print("yes")

In [15]:
words_related_to_tour = ['tour', 'trips', 'tours']
mask = data['subtype'].apply(lambda x: not any(any(word in s.lower() for word in words_related_to_tour) for s in x))
filtered_data = data[mask]

In [16]:
filtered_data.head()

,reviewTags,ancestorLocations,nearestMetroStations,subcategories,subtype,rankingString,name,latitude,ratingHistogram,numberOfReviews,...,locationString,rating,type,rankingPosition,category,localName,id,description,rawRanking,rankingDenominator
1,[],"[{'id': '635747', 'name': 'Baga', 'abbreviatio...",[],"[Zoos & Aquariums, Water & Amusement Parks, Fu...","[Theme Parks, Aquariums, Game & Entertainment ...",#1 of 2 Fun & Games in Baga,Goosebumps Virtual Escape,15.555789,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",82,...,"Baga, North Goa District, Goa",5.0,ATTRACTION,1,attraction,Goosebumps Virtual Escape,25073480,Goosebumps- virtual escape Let's walk into vir...,4.418244,2
2,[],"[{'id': '297668', 'name': 'Jodhpur', 'abbrevia...",[],[Sights & Landmarks],"[Ancient Ruins, Architectural Buildings]",#1 of 103 things to do in Jodhpur,Walk to blueCity heritagetour,26.297567,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",112,...,"Jodhpur, Jodhpur District, Rajasthan",5.0,ATTRACTION,1,attraction,Walk to blueCity heritagetour,15694922,Blue City heritage tour is walk to blueCity ar...,4.416904,103
3,[],"[{'id': '297633', 'name': 'Kochi (Cochin)', 'a...",[],[Transportation],[Taxis & Shuttles],#1 of 220 Transportation in Kochi (Cochin),J & J Taxi Service,9.970154,"{'count1': 4, 'count2': 2, 'count3': 6, 'count...",1426,...,"Kochi (Cochin), Ernakulam District, Kerala",5.0,ATTRACTION,1,attraction,J & J Taxi Service,13155645,"Welcome To J&J Taxi Service, we are one of the...",4.483928,220
4,[],"[{'id': '304554', 'name': 'Mumbai', 'abbreviat...",[],[Spas & Wellness],"[Yoga & Pilates, Hammams & Turkish Baths, Spas]",#2 of 226 Spas & Wellness in Mumbai,Muktaa The Wellness Clinic & Luxury Spa Marine...,18.930307,"{'count1': 4, 'count2': 2, 'count3': 2, 'count...",1031,...,"Mumbai, Maharashtra",5.0,ATTRACTION,2,attraction,Muktaa The Wellness Clinic & Luxury Spa Marine...,13174371,"The name Muktaa comes from the Indian origin, ...",4.502504,226
5,[],"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[],[Spas & Wellness],[Spas],#1 of 104 Spas & Wellness in Jaipur,Kerala Ayurveda Kendra,26.936825,"{'count1': 9, 'count2': 8, 'count3': 20, 'coun...",1252,...,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,1,attraction,Kerala Ayurveda Kendra,1438098,We have just one location in Jaipur-we don't h...,4.462176,104

In [17]:
filtered_data.shape

(619, 21)

In [18]:
filtered_data.tail()

,reviewTags,ancestorLocations,nearestMetroStations,subcategories,subtype,rankingString,name,latitude,ratingHistogram,numberOfReviews,...,locationString,rating,type,rankingPosition,category,localName,id,description,rawRanking,rankingDenominator
1003,[],"[{'id': '12432580', 'name': 'Shegaon', 'abbrev...",[],[Sights & Landmarks],[Sacred & Religious Sites],#1 of 3 things to do in Shegaon,Gajanan Maharaj Temple,NaN,"{'count1': 0, 'count2': 0, 'count3': 1, 'count...",42,...,"Shegaon, Buldhana District, Maharashtra",5.0,ATTRACTION,1,attraction,Gajanan Maharaj Temple,12883819,None,3.333700,3
1004,[],"[{'id': '297636', 'name': 'Thekkady', 'abbrevi...",[],[Nature & Parks],[Waterfalls],#20 of 36 things to do in Thekkady,Pandikuzhi Waterfalls,9.643201,"{'count1': 1, 'count2': 3, 'count3': 6, 'count...",27,...,"Thekkady, Idukki District, Kerala",3.5,ATTRACTION,20,attraction,Pandikuzhi Waterfalls,10629484,"Pandikuzhi, about five km from Kumily, is one ...",2.828965,36
1005,[],"[{'id': '1162496', 'name': 'Meerut', 'abbrevia...",[],[Shopping],[Shopping Malls],#2 of 20 things to do in Meerut,The Shopprix Mall,28.948483,"{'count1': 3, 'count2': 4, 'count3': 13, 'coun...",86,...,"Meerut, Meerut District, Uttar Pradesh",4.0,ATTRACTION,2,attraction,The Shopprix Mall,8114119,None,3.041268,20
1006,"[{'text': 'coracle ride', 'reviews': 109}, {'t...","[{'id': '1676038', 'name': 'Hogenakkal', 'abbr...",[],[Nature & Parks],[Waterfalls],#2 of 18 things to do in Hogenakkal,Hogenakkal Falls,12.118337,"{'count1': 88, 'count2': 65, 'count3': 122, 'c...",585,...,"Hogenakkal, Dharmapuri District, Tamil Nadu",3.5,ATTRACTION,2,attraction,Hogenakkal Falls,1223598,None,2.989753,18
1007,[],"[{'id': '1893710', 'name': 'Deoghar', 'abbrevi...",[],[Sights & Landmarks],[Sacred & Religious Sites],#2 of 19 things to do in Deoghar,Basukinath Temple,24.386356,"{'count1': 1, 'count2': 0, 'count3': 9, 'count...",81,...,"Deoghar, Deoghar District, Jharkhand",4.5,ATTRACTION,2,attraction,Basukinath Temple,4138779,None,3.297912,19

In [19]:
filtered_data.isnull().sum()

reviewTags                0
ancestorLocations         0
nearestMetroStations      0
subcategories             0
subtype                   0
rankingString             0
name                      0
latitude                 49
ratingHistogram           0
numberOfReviews           0
longitude                49
locationString            0
rating                    0
type                      0
rankingPosition           0
category                  0
localName                 0
id                        0
description             475
rawRanking                0
rankingDenominator        0
dtype: int64

In [20]:
filtered_data= filtered_data.drop(columns=["latitude" , "longitude", "description"])

In [21]:
filtered_data.head()

,reviewTags,ancestorLocations,nearestMetroStations,subcategories,subtype,rankingString,name,ratingHistogram,numberOfReviews,locationString,rating,type,rankingPosition,category,localName,id,rawRanking,rankingDenominator
1,[],"[{'id': '635747', 'name': 'Baga', 'abbreviatio...",[],"[Zoos & Aquariums, Water & Amusement Parks, Fu...","[Theme Parks, Aquariums, Game & Entertainment ...",#1 of 2 Fun & Games in Baga,Goosebumps Virtual Escape,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",82,"Baga, North Goa District, Goa",5.0,ATTRACTION,1,attraction,Goosebumps Virtual Escape,25073480,4.418244,2
2,[],"[{'id': '297668', 'name': 'Jodhpur', 'abbrevia...",[],[Sights & Landmarks],"[Ancient Ruins, Architectural Buildings]",#1 of 103 things to do in Jodhpur,Walk to blueCity heritagetour,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",112,"Jodhpur, Jodhpur District, Rajasthan",5.0,ATTRACTION,1,attraction,Walk to blueCity heritagetour,15694922,4.416904,103
3,[],"[{'id': '297633', 'name': 'Kochi (Cochin)', 'a...",[],[Transportation],[Taxis & Shuttles],#1 of 220 Transportation in Kochi (Cochin),J & J Taxi Service,"{'count1': 4, 'count2': 2, 'count3': 6, 'count...",1426,"Kochi (Cochin), Ernakulam District, Kerala",5.0,ATTRACTION,1,attraction,J & J Taxi Service,13155645,4.483928,220
4,[],"[{'id': '304554', 'name': 'Mumbai', 'abbreviat...",[],[Spas & Wellness],"[Yoga & Pilates, Hammams & Turkish Baths, Spas]",#2 of 226 Spas & Wellness in Mumbai,Muktaa The Wellness Clinic & Luxury Spa Marine...,"{'count1': 4, 'count2': 2, 'count3': 2, 'count...",1031,"Mumbai, Maharashtra",5.0,ATTRACTION,2,attraction,Muktaa The Wellness Clinic & Luxury Spa Marine...,13174371,4.502504,226
5,[],"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[],[Spas & Wellness],[Spas],#1 of 104 Spas & Wellness in Jaipur,Kerala Ayurveda Kendra,"{'count1': 9, 'count2': 8, 'count3': 20, 'coun...",1252,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,1,attraction,Kerala Ayurveda Kendra,1438098,4.462176,104

In [22]:
filtered_data["reviewTags"]

1                                                      []
2                                                      []
3                                                      []
4                                                      []
5                                                      []
                              ...
1003                                                   []
1004                                                   []
1005                                                   []
1006    [{'text': 'coracle ride', 'reviews': 109}, {'t...
1007                                                   []
Name: reviewTags, Length: 619, dtype: object

In [23]:
filtered_data["subtype"].explode().unique()

array(['Theme Parks', 'Aquariums', 'Game & Entertainment Centers',
       'Ancient Ruins', 'Architectural Buildings', 'Taxis & Shuttles',
       'Yoga & Pilates', 'Hammams & Turkish Baths', 'Spas',
       'Gift & Specialty Shops', 'Sacred & Religious Sites',
       'Nature & Wildlife Areas', 'Points of Interest & Landmarks',
       'Monuments & Statues', 'Art Galleries', 'Castles',
       'Observation Decks & Towers', 'Historic Sites', 'Gardens',
       'Shopping Malls', 'Art Museums', 'Cooking Classes',
       'Health/Fitness Clubs & Gyms', 'Factory Outlets', 'Safaris',
       'Bus Transportation', 'Lessons & Workshops', 'Antique Stores',
       'Sports Camps & Clinics', 'Concerts', 'Parasailing & Paragliding',
       'Zipline & Aerial Adventure Parks', 'River Rafting & Tubing',
       'Bodies of Water', 'Zoos', 'Parks', 'Beaches', 'Waterfalls',
       'Deserts', 'Caverns & Caves', 'National Parks', 'History Museums',
       'Mountains', 'Valleys', 'Specialty Museums', 'Scenic Drives',
       'Neighborhoods', 'Geologic Formations', 'Dams', 'Lookouts',
       'Ski & Snowboard Areas', 'Forests', 'Arenas & Stadiums', 'Islands',
       'Lighthouses', 'Hiking Trails', 'Hot Springs & Geysers',
       'Cultural Events', 'Flea & Street Markets', 'Bridges',
       'Mass Transportation Systems', 'Tramways', 'Gondola Cruises',
       'Casinos', 'Churches & Cathedrals', 'Scenic Railroads',
       'Cemeteries', 'Farms', 'Science Museums',
       'Observatories & Planetariums', 'Water Parks', 'Libraries',
       'Military Museums', 'Historic Walking Areas', 'Theaters',
       'Educational sites', 'Playgrounds', 'Department Stores',
       'Wineries & Vineyards'], dtype=object)

In [24]:
l = data["subtype"].apply(lambda x :   any("Neighborhoods" in s for s in x ))

In [25]:
new_df = data.loc[l,"name"]

In [26]:
new_df.head()

530    Raghurajpur Artist Village
896                       MG Marg
967                 Nariman Point
Name: name, dtype: object

In [27]:
data.iloc[896]

reviewTags                                                             []
ancestorLocations       [{'id': '659796', 'name': 'Gangtok', 'abbrevia...
nearestMetroStations                                                   []
subcategories                                 [Sights & Landmarks, Other]
subtype                                                   [Neighborhoods]
rankingString                            #5 of 54 things to do in Gangtok
name                                                              MG Marg
latitude                                                         27.33081
ratingHistogram         {'count1': 2, 'count2': 9, 'count3': 136, 'cou...
numberOfReviews                                                      1386
longitude                                                        88.61347
locationString                               Gangtok, East Sikkim, Sikkim
rating                                                                4.5
type                                                           ATTRACTION
rankingPosition                                                         5
category                                                       attraction
localName                                                         MG Marg
id                                                                6961638
description                                                          None
rawRanking                                                        3.97471
rankingDenominator                                                     54
Name: 896, dtype: object

In [28]:
words_related_to_tour = ['Taxis & Shuttles', 'Bus Transportation', 'Lessons & Workshops',"Neighborhoods",'Health/Fitness Clubs & Gyms','Mass Transportation Systems', 'Arenas & Stadiums','Department Stores',"Factory Outlets","Sports Camps & Clinics","Yoga & Pilates"]

In [29]:
words_related_to_tour = [x.lower() for x in words_related_to_tour]

In [30]:
words_related_to_tour

['taxis & shuttles',
 'bus transportation',
 'lessons & workshops',
 'neighborhoods',
 'health/fitness clubs & gyms',
 'mass transportation systems',
 'arenas & stadiums',
 'department stores',
 'factory outlets',
 'sports camps & clinics',
 'yoga & pilates']

In [31]:
mask = filtered_data['subtype'].apply(lambda x: not any(any(word in s.lower() for word in words_related_to_tour) for s in x))
filtered_data = filtered_data[mask]

In [32]:
filtered_data["subtype"].explode().unique()

array(['Theme Parks', 'Aquariums', 'Game & Entertainment Centers',
       'Ancient Ruins', 'Architectural Buildings', 'Spas',
       'Gift & Specialty Shops', 'Sacred & Religious Sites',
       'Nature & Wildlife Areas', 'Points of Interest & Landmarks',
       'Monuments & Statues', 'Art Galleries', 'Castles',
       'Observation Decks & Towers', 'Historic Sites', 'Gardens',
       'Shopping Malls', 'Art Museums', 'Cooking Classes',
       'Antique Stores', 'Hammams & Turkish Baths',
       'Parasailing & Paragliding', 'Zipline & Aerial Adventure Parks',
       'River Rafting & Tubing', 'Bodies of Water', 'Zoos', 'Parks',
       'Beaches', 'Waterfalls', 'Deserts', 'Caverns & Caves',
       'National Parks', 'History Museums', 'Mountains', 'Valleys',
       'Specialty Museums', 'Scenic Drives', 'Geologic Formations',
       'Dams', 'Lookouts', 'Ski & Snowboard Areas', 'Forests', 'Islands',
       'Lighthouses', 'Hiking Trails', 'Hot Springs & Geysers',
       'Cultural Events', 'Flea & Street Markets', 'Bridges', 'Tramways',
       'Gondola Cruises', 'Casinos', 'Churches & Cathedrals',
       'Scenic Railroads', 'Cemeteries', 'Farms', 'Science Museums',
       'Observatories & Planetariums', 'Water Parks', 'Libraries',
       'Military Museums', 'Historic Walking Areas', 'Theaters',
       'Educational sites', 'Playgrounds', 'Wineries & Vineyards'],
      dtype=object)

In [33]:
"Factory Outlets","Sports Camps & Clinics","Yoga & Pilates"

('Factory Outlets', 'Sports Camps & Clinics', 'Yoga & Pilates')

In [34]:
filtered_data.head()

,reviewTags,ancestorLocations,nearestMetroStations,subcategories,subtype,rankingString,name,ratingHistogram,numberOfReviews,locationString,rating,type,rankingPosition,category,localName,id,rawRanking,rankingDenominator
1,[],"[{'id': '635747', 'name': 'Baga', 'abbreviatio...",[],"[Zoos & Aquariums, Water & Amusement Parks, Fu...","[Theme Parks, Aquariums, Game & Entertainment ...",#1 of 2 Fun & Games in Baga,Goosebumps Virtual Escape,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",82,"Baga, North Goa District, Goa",5.0,ATTRACTION,1,attraction,Goosebumps Virtual Escape,25073480,4.418244,2
2,[],"[{'id': '297668', 'name': 'Jodhpur', 'abbrevia...",[],[Sights & Landmarks],"[Ancient Ruins, Architectural Buildings]",#1 of 103 things to do in Jodhpur,Walk to blueCity heritagetour,"{'count1': 0, 'count2': 0, 'count3': 0, 'count...",112,"Jodhpur, Jodhpur District, Rajasthan",5.0,ATTRACTION,1,attraction,Walk to blueCity heritagetour,15694922,4.416904,103
5,[],"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[],[Spas & Wellness],[Spas],#1 of 104 Spas & Wellness in Jaipur,Kerala Ayurveda Kendra,"{'count1': 9, 'count2': 8, 'count3': 20, 'coun...",1252,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,1,attraction,Kerala Ayurveda Kendra,1438098,4.462176,104
6,[],"[{'id': '319729', 'name': 'Pushkar', 'abbrevia...",[],[Fun & Games],[Game & Entertainment Centers],#1 of 1 Fun & Games in Pushkar,Xcapade Adventures,"{'count1': 2, 'count2': 3, 'count3': 3, 'count...",701,"Pushkar, Ajmer District, Rajasthan",5.0,ATTRACTION,1,attraction,Xcapade Adventures,11982955,4.450218,1
8,"[{'text': 'mr anil', 'reviews': 41}, {'text': ...","[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[],[Shopping],[Gift & Specialty Shops],#4 of 441 Shopping in Jaipur,Jaipur Blue Pottery Art Centre,"{'count1': 7, 'count2': 3, 'count3': 6, 'count...",1217,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,4,attraction,Jaipur Blue Pottery Art Centre,12399790,4.452539,441

In [35]:
to_drop = ["reviewTags", 'nearestMetroStations','id', 'ratingHistogram', 'rankingPosition','rankingDenominator','rankingString']

In [36]:
df = filtered_data.copy()

In [37]:
df.drop(columns=to_drop, inplace = True)

In [38]:
df.head()

,ancestorLocations,subcategories,subtype,name,numberOfReviews,locationString,rating,type,category,localName,rawRanking
1,"[{'id': '635747', 'name': 'Baga', 'abbreviatio...","[Zoos & Aquariums, Water & Amusement Parks, Fu...","[Theme Parks, Aquariums, Game & Entertainment ...",Goosebumps Virtual Escape,82,"Baga, North Goa District, Goa",5.0,ATTRACTION,attraction,Goosebumps Virtual Escape,4.418244
2,"[{'id': '297668', 'name': 'Jodhpur', 'abbrevia...",[Sights & Landmarks],"[Ancient Ruins, Architectural Buildings]",Walk to blueCity heritagetour,112,"Jodhpur, Jodhpur District, Rajasthan",5.0,ATTRACTION,attraction,Walk to blueCity heritagetour,4.416904
5,"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[Spas & Wellness],[Spas],Kerala Ayurveda Kendra,1252,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,attraction,Kerala Ayurveda Kendra,4.462176
6,"[{'id': '319729', 'name': 'Pushkar', 'abbrevia...",[Fun & Games],[Game & Entertainment Centers],Xcapade Adventures,701,"Pushkar, Ajmer District, Rajasthan",5.0,ATTRACTION,attraction,Xcapade Adventures,4.450218
8,"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[Shopping],[Gift & Specialty Shops],Jaipur Blue Pottery Art Centre,1217,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,attraction,Jaipur Blue Pottery Art Centre,4.452539

In [39]:
df['subcategories'].explode().unique()

array(['Zoos & Aquariums', 'Water & Amusement Parks', 'Fun & Games',
       'Nature & Parks', 'Sights & Landmarks', 'Spas & Wellness',
       'Shopping', 'Museums', 'Food & Drink', 'Classes & Workshops',
       'Other', 'Tours', 'Boat Tours & Water Sports',
       'Outdoor Activities', 'Events', 'Transportation',
       'Casinos & Gambling', 'Traveler Resources', 'Concerts & Shows'],
      dtype=object)

In [40]:
df['subtype'].explode().unique()

array(['Theme Parks', 'Aquariums', 'Game & Entertainment Centers',
       'Ancient Ruins', 'Architectural Buildings', 'Spas',
       'Gift & Specialty Shops', 'Sacred & Religious Sites',
       'Nature & Wildlife Areas', 'Points of Interest & Landmarks',
       'Monuments & Statues', 'Art Galleries', 'Castles',
       'Observation Decks & Towers', 'Historic Sites', 'Gardens',
       'Shopping Malls', 'Art Museums', 'Cooking Classes',
       'Antique Stores', 'Hammams & Turkish Baths',
       'Parasailing & Paragliding', 'Zipline & Aerial Adventure Parks',
       'River Rafting & Tubing', 'Bodies of Water', 'Zoos', 'Parks',
       'Beaches', 'Waterfalls', 'Deserts', 'Caverns & Caves',
       'National Parks', 'History Museums', 'Mountains', 'Valleys',
       'Specialty Museums', 'Scenic Drives', 'Geologic Formations',
       'Dams', 'Lookouts', 'Ski & Snowboard Areas', 'Forests', 'Islands',
       'Lighthouses', 'Hiking Trails', 'Hot Springs & Geysers',
       'Cultural Events', 'Flea & Street Markets', 'Bridges', 'Tramways',
       'Gondola Cruises', 'Casinos', 'Churches & Cathedrals',
       'Scenic Railroads', 'Cemeteries', 'Farms', 'Science Museums',
       'Observatories & Planetariums', 'Water Parks', 'Libraries',
       'Military Museums', 'Historic Walking Areas', 'Theaters',
       'Educational sites', 'Playgrounds', 'Wineries & Vineyards'],
      dtype=object)

In [41]:
df['rating'].unique()

array([5. , 4. , 4.5, 3.5, 3. ])

In [42]:
sum(df['localName'] == df['name'])

568

In [43]:
df['name'].shape

(571,)

In [44]:
df["ancestorLocations"].iloc[0]

[{'id': '635747',
  'name': 'Baga',
  'abbreviation': None,
  'subcategory': 'Municipality'},
 {'id': '12412660',
  'name': 'North Goa District',
  'abbreviation': None,
  'subcategory': 'District'},
 {'id': '297604',
  'name': 'Goa',
  'abbreviation': None,
  'subcategory': 'Region'},
 {'id': '293860',
  'name': 'India',
  'abbreviation': None,
  'subcategory': 'Country'}]

In [45]:
df["ancestorLocations"]

1       [{'id': '635747', 'name': 'Baga', 'abbreviatio...
2       [{'id': '297668', 'name': 'Jodhpur', 'abbrevia...
5       [{'id': '304555', 'name': 'Jaipur', 'abbreviat...
6       [{'id': '319729', 'name': 'Pushkar', 'abbrevia...
8       [{'id': '304555', 'name': 'Jaipur', 'abbreviat...
                              ...
1003    [{'id': '12432580', 'name': 'Shegaon', 'abbrev...
1004    [{'id': '297636', 'name': 'Thekkady', 'abbrevi...
1005    [{'id': '1162496', 'name': 'Meerut', 'abbrevia...
1006    [{'id': '1676038', 'name': 'Hogenakkal', 'abbr...
1007    [{'id': '1893710', 'name': 'Deoghar', 'abbrevi...
Name: ancestorLocations, Length: 571, dtype: object

In [46]:
df.head()

,ancestorLocations,subcategories,subtype,name,numberOfReviews,locationString,rating,type,category,localName,rawRanking
1,"[{'id': '635747', 'name': 'Baga', 'abbreviatio...","[Zoos & Aquariums, Water & Amusement Parks, Fu...","[Theme Parks, Aquariums, Game & Entertainment ...",Goosebumps Virtual Escape,82,"Baga, North Goa District, Goa",5.0,ATTRACTION,attraction,Goosebumps Virtual Escape,4.418244
2,"[{'id': '297668', 'name': 'Jodhpur', 'abbrevia...",[Sights & Landmarks],"[Ancient Ruins, Architectural Buildings]",Walk to blueCity heritagetour,112,"Jodhpur, Jodhpur District, Rajasthan",5.0,ATTRACTION,attraction,Walk to blueCity heritagetour,4.416904
5,"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[Spas & Wellness],[Spas],Kerala Ayurveda Kendra,1252,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,attraction,Kerala Ayurveda Kendra,4.462176
6,"[{'id': '319729', 'name': 'Pushkar', 'abbrevia...",[Fun & Games],[Game & Entertainment Centers],Xcapade Adventures,701,"Pushkar, Ajmer District, Rajasthan",5.0,ATTRACTION,attraction,Xcapade Adventures,4.450218
8,"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[Shopping],[Gift & Specialty Shops],Jaipur Blue Pottery Art Centre,1217,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,attraction,Jaipur Blue Pottery Art Centre,4.452539

In [47]:
df['Region'] = df['locationString'].apply(lambda x: x.split(',')[-2].strip() if isinstance(x, str) and len(x.split(',')) > 1 else None)
df['District'] = df['locationString'].apply(lambda x: x.split(',')[-3].strip() if isinstance(x, str) and len(x.split(',')) > 2 else None)

# def get_region(locations):
#     for loc in locations:
#         if loc.get('subcategory') == 'Region':
#             return loc.get('name')
#     return None

# def get_district(locations):
#     for loc in locations:
#         if loc.get('subcategory') == 'District':
#             return loc.get('name')
#     return None

# # Extract Region and District from the 'ancestorLocations' column
# df['Region'] = df['ancestorLocations'].apply(get_region)
# df['District'] = df['ancestorLocations'].apply(get_district)

In [48]:
df.head()

,ancestorLocations,subcategories,subtype,name,numberOfReviews,locationString,rating,type,category,localName,rawRanking,Region,District
1,"[{'id': '635747', 'name': 'Baga', 'abbreviatio...","[Zoos & Aquariums, Water & Amusement Parks, Fu...","[Theme Parks, Aquariums, Game & Entertainment ...",Goosebumps Virtual Escape,82,"Baga, North Goa District, Goa",5.0,ATTRACTION,attraction,Goosebumps Virtual Escape,4.418244,North Goa District,Baga
2,"[{'id': '297668', 'name': 'Jodhpur', 'abbrevia...",[Sights & Landmarks],"[Ancient Ruins, Architectural Buildings]",Walk to blueCity heritagetour,112,"Jodhpur, Jodhpur District, Rajasthan",5.0,ATTRACTION,attraction,Walk to blueCity heritagetour,4.416904,Jodhpur District,Jodhpur
5,"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[Spas & Wellness],[Spas],Kerala Ayurveda Kendra,1252,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,attraction,Kerala Ayurveda Kendra,4.462176,Jaipur District,Jaipur
6,"[{'id': '319729', 'name': 'Pushkar', 'abbrevia...",[Fun & Games],[Game & Entertainment Centers],Xcapade Adventures,701,"Pushkar, Ajmer District, Rajasthan",5.0,ATTRACTION,attraction,Xcapade Adventures,4.450218,Ajmer District,Pushkar
8,"[{'id': '304555', 'name': 'Jaipur', 'abbreviat...",[Shopping],[Gift & Specialty Shops],Jaipur Blue Pottery Art Centre,1217,"Jaipur, Jaipur District, Rajasthan",5.0,ATTRACTION,attraction,Jaipur Blue Pottery Art Centre,4.452539,Jaipur District,Jaipur

In [49]:
drop=["ancestorLocations", 'type', 'category','localName','locationString']
df.drop(columns=drop , inplace=True)

In [50]:
df.head()

,subcategories,subtype,name,numberOfReviews,rating,rawRanking,Region,District
1,"[Zoos & Aquariums, Water & Amusement Parks, Fu...","[Theme Parks, Aquariums, Game & Entertainment ...",Goosebumps Virtual Escape,82,5.0,4.418244,North Goa District,Baga
2,[Sights & Landmarks],"[Ancient Ruins, Architectural Buildings]",Walk to blueCity heritagetour,112,5.0,4.416904,Jodhpur District,Jodhpur
5,[Spas & Wellness],[Spas],Kerala Ayurveda Kendra,1252,5.0,4.462176,Jaipur District,Jaipur
6,[Fun & Games],[Game & Entertainment Centers],Xcapade Adventures,701,5.0,4.450218,Ajmer District,Pushkar
8,[Shopping],[Gift & Specialty Shops],Jaipur Blue Pottery Art Centre,1217,5.0,4.452539,Jaipur District,Jaipur

In [51]:
df.columns

Index(['subcategories', 'subtype', 'name', 'numberOfReviews', 'rating',
       'rawRanking', 'Region', 'District'],
      dtype='object')

In [52]:
df['subcategories'] = df['subcategories'].apply(lambda x: ', '.join(x))

# Convert lists in 'subtype' column to strings
df['subtype'] = df['subtype'].apply(lambda x: ', '.join(x))

In [53]:
df.head()

,subcategories,subtype,name,numberOfReviews,rating,rawRanking,Region,District
1,"Zoos & Aquariums, Water & Amusement Parks, Fun...","Theme Parks, Aquariums, Game & Entertainment C...",Goosebumps Virtual Escape,82,5.0,4.418244,North Goa District,Baga
2,Sights & Landmarks,"Ancient Ruins, Architectural Buildings",Walk to blueCity heritagetour,112,5.0,4.416904,Jodhpur District,Jodhpur
5,Spas & Wellness,Spas,Kerala Ayurveda Kendra,1252,5.0,4.462176,Jaipur District,Jaipur
6,Fun & Games,Game & Entertainment Centers,Xcapade Adventures,701,5.0,4.450218,Ajmer District,Pushkar
8,Shopping,Gift & Specialty Shops,Jaipur Blue Pottery Art Centre,1217,5.0,4.452539,Jaipur District,Jaipur

In [54]:
df.reset_index(drop=True ,inplace=True)

In [55]:
df.head()

,subcategories,subtype,name,numberOfReviews,rating,rawRanking,Region,District
0,"Zoos & Aquariums, Water & Amusement Parks, Fun...","Theme Parks, Aquariums, Game & Entertainment C...",Goosebumps Virtual Escape,82,5.0,4.418244,North Goa District,Baga
1,Sights & Landmarks,"Ancient Ruins, Architectural Buildings",Walk to blueCity heritagetour,112,5.0,4.416904,Jodhpur District,Jodhpur
2,Spas & Wellness,Spas,Kerala Ayurveda Kendra,1252,5.0,4.462176,Jaipur District,Jaipur
3,Fun & Games,Game & Entertainment Centers,Xcapade Adventures,701,5.0,4.450218,Ajmer District,Pushkar
4,Shopping,Gift & Specialty Shops,Jaipur Blue Pottery Art Centre,1217,5.0,4.452539,Jaipur District,Jaipur

In [56]:
# df.to_csv("Tourismdfs.csv",index=False)

# Model Building

In [58]:
from surprise import Dataset, Reader, KNNBasic
from surprise.model_selection import train_test_split
from surprise import accuracy

In [146]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from sklearn.metrics.pairwise import linear_kernel

In [65]:

# Load data
# Assuming df is your DataFrame containing the provided data

# Combine subcategories and subtype into a single text column for each place
df['features'] = df['subcategories'] + ', ' + df['subtype']

In [66]:

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the features
tfidf_matrix = tfidf_vectorizer.fit_transform(df['features'])

# Calculate cosine similarity between places
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [69]:
# Function to recommend places based on user preferences
def recommend_places(location, subcategory, subtype):
    # Filter places based on location, subcategory, and subtype
    filtered_df = df[(df['Region'] == location) & (df['subcategories'].str.contains(subcategory)) & (df['subtype'].str.contains(subtype))]
    
    # Get indices of filtered places
    indices = filtered_df.index
    
    # Calculate similarity scores for filtered places
    sim_scores = list(enumerate(cosine_sim[indices]))
    
    # Sort places by similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get indices of recommended places in descending order of relevance
    top_indices = [i[0] for i in sim_scores]
    
    # Return recommended places ranking-wise
    return df.iloc[top_indices][['name', 'rating', 'rawRanking']]

# Example usage
location = 'North Goa District'
subcategory = 'Zoos & Aquariums'
subtype = 'Theme Parks'
recommendations = recommend_places(location, subcategory, subtype)
print(recommendations)

                        name  rating  rawRanking
1  Goosebumps Virtual Escape     5.0    4.418244

In [ ]:
# Function to recommend places based on user preferences
def recommend_places(location, subtype):
    # Filter places based on location and subtype
    filtered_df = df[(df['Region'] == location) & (df['subcategories'].str.contains(subtype))]
    
    if filtered_df.empty:
        return "No matching places found."
    
    # Calculate similarity scores for filtered places
    sim_scores = list(enumerate(cosine_sim[filtered_df.index]))
    
    # Sort places by similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get indices of recommended places in descending order of relevance
    top_indices = [i[0] for i in sim_scores]
    
    # Return all recommended places ranking-wise
    return df.loc[filtered_df.index[top_indices]][['name', 'rating', 'rawRanking']]

# Example usage
location = 'Pune District'
# subtype = 'Theme Parks'
subtype = 'Water & Amusement Parks'
recommendations = recommend_places(location, subtype)
print(recommendations)

In [155]:
def recommend_places(dataset, region, subcategory):
    # Step 1: Filter dataset by region and subcategory
    filtered_data = dataset[(dataset['Region'] == region) & (dataset['subcategories'] == subcategory)]

    if filtered_data.empty:
        return "No recommendations found for the selected region and subcategory."

    # Step 2: Define a method to calculate recommendation score
    def calculate_score(row):
        # Define your scoring mechanism based on relevant features
        # For example, a simple score can be a combination of rating and number of reviews
        return row['rating'] * row['numberOfReviews']

    # Step 3: Calculate recommendation score for each place
    filtered_data['recommendation_score'] = filtered_data.apply(calculate_score, axis=1)

    # Step 4: Sort by recommendation score in descending order
    recommended_places = filtered_data.sort_values(by='recommendation_score', ascending=False)

    # Display recommended places
    return recommended_places[['name', 'rating', 'numberOfReviews', 'recommendation_score']]

# Example usage:
# Assuming dataset is your loaded DataFrame
region = 'Pune District'
subcategory = 'Water & Amusement Parks'
recommended_places = recommend_places(df.copy(), region, subcategory)
print(recommended_places)

                                      name  rating  numberOfReviews  \
11                    Della Adventure Park     4.5             5304
324  Wet N Joy Water Park & Amusement Park     4.0              200

     recommendation_score
11                23868.0
324                 800.0

C:\Users\DEVAVRAT\AppData\Local\Temp\ipykernel_21520\1823390991.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['recommendation_score'] = filtered_data.apply(calculate_score, axis=1)

In [167]:
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.feature_extraction.text import TfidfVectorizer
# import numpy as np

def recommend_places_with_similarity(dataset, region, subcategory):
    # Step 1: Filter dataset by region and subcategory
    filtered_data = dataset[(dataset['Region'] == region) & (dataset['subcategories'] == subcategory)]

    if filtered_data.empty:
        return "No recommendations found for the selected region and subcategory."

    # Step 2: Vectorize the combined features
    vectorizer = TfidfVectorizer()
    combined_features_matrix = vectorizer.fit_transform(filtered_data['combined_features'])

    # Step 3: Calculate cosine similarity
    similarity_matrix = cosine_similarity(combined_features_matrix, combined_features_matrix)

    # Step 4: Get indices of places in descending order of similarity
    sim_scores = list(enumerate(similarity_matrix[-1]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[0:]  # Exclude the place itself

    # Step 5: Get top recommendations
    top_indices = [x[0] for x in sim_scores]
    top_recommendations = filtered_data.iloc[top_indices]

    return top_recommendations[['name', 'rating', 'numberOfReviews']]

# Example usage:
# Assuming dataset is your loaded DataFrame

In [174]:
# def calculate_recommendation_score(row):
#     # Calculate recommendation score based on the number of reviews
#     return row['numberOfReviews']/row["rawRanking"]

# def recommend_places_with_similarity(dataset, region, subcategory):
#     # Step 1: Filter dataset by region and subcategory
#     filtered_data = dataset[(dataset['Region'] == region) & (dataset['subcategories'] == subcategory)]

#     if filtered_data.empty:
#         return "No recommendations found for the selected region and subcategory."

#     # Step 2: Calculate recommendation score based on number of reviews
#     filtered_data['recommendation_score'] = filtered_data.apply(calculate_recommendation_score, axis=1)

#     # Step 3: Vectorize the subcategory and subtype
#     vectorizer = TfidfVectorizer()
#     subcategory_subtype_matrix = vectorizer.fit_transform(filtered_data['subcategories'] + ' ' + filtered_data['subtype'])

#     # Step 4: Calculate cosine similarity
#     similarity_matrix = cosine_similarity(subcategory_subtype_matrix, subcategory_subtype_matrix)

#     # Step 5: Get indices of places in descending order of similarity
#     sim_scores = list(enumerate(similarity_matrix[-1]))
#     sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
#     sim_scores = sim_scores[0:]  # Exclude the place itself

#     # Step 6: Get top recommendations based on similarity and recommendation score
#     top_indices = [x[0] for x in sim_scores]
#     top_recommendations = filtered_data.iloc[top_indices].sort_values(by=['recommendation_score'], ascending=False)

#     return top_recommendations[['name', 'rating', 'numberOfReviews', 'recommendation_score']]

# # Example usage:
# # Assuming dataset is your loaded DataFrame

In [175]:
# region = 'Pune District'
# subcategory = 'Water & Amusement Parks'
# recommended_places = recommend_places_with_similarity(df, region, subcategory)
# print(recommended_places)

                                      name  rating  numberOfReviews  \
11                    Della Adventure Park     4.5             5304
324  Wet N Joy Water Park & Amusement Park     4.0              200

     recommendation_score
11            1197.061891
324             65.391495

C:\Users\DEVAVRAT\AppData\Local\Temp\ipykernel_21520\129177307.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['recommendation_score'] = filtered_data.apply(calculate_recommendation_score, axis=1)

In [170]:
# region = 'Jaipur District'
# subcategory = 'Sights & Landmarks'
# recommended_places = recommend_places_with_similarity(df, region, subcategory)
# print(recommended_places)

                                   name  rating  numberOfReviews
147                        Patrika Gate     4.5               84
240                Gatore Ki Chhatriyan     4.5               92
15                         Amber Palace     4.5            18542
55                            Jal Mahal     4.0             3932
159                 Royal Gaitor Tumbas     4.5              335
59                        Monkey Temple     4.0             1959
62   Khole Ke Hanuman JI Temple, Jaipur     4.5              269
95                       Galtaji Temple     4.0              378
253                 Govind Devji Temple     4.5              709

In [176]:
# region = 'Jaipur District'
# subcategory = 'Sights & Landmarks'
# recommended_places = recommend_places_with_similarity(df, region, subcategory)
# print(recommended_places)

                                   name  rating  numberOfReviews  \
15                         Amber Palace     4.5            18542
55                            Jal Mahal     4.0             3932
59                        Monkey Temple     4.0             1959
253                 Govind Devji Temple     4.5              709
95                       Galtaji Temple     4.0              378
159                 Royal Gaitor Tumbas     4.5              335
62   Khole Ke Hanuman JI Temple, Jaipur     4.5              269
240                Gatore Ki Chhatriyan     4.5               92
147                        Patrika Gate     4.5               84

     recommendation_score
15            3708.400000
55            1160.104874
59             559.830522
253            170.659909
95             117.465928
159             85.363957
62              75.253954
240             26.617689
147             23.019665

C:\Users\DEVAVRAT\AppData\Local\Temp\ipykernel_21520\129177307.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['recommendation_score'] = filtered_data.apply(calculate_recommendation_score, axis=1)

In [177]:
dataset = df.copy()

In [178]:
# def get_user_input(prompt, options):
#     while True:
#         print(prompt)
#         for idx, option in enumerate(options, start=1):
#             print(f"{idx}. {option}")
#         choice = input("Enter your choice (1-{}): ".format(len(options)))
#         if choice.isdigit() and 1 <= int(choice) <= len(options):
#             return options[int(choice) - 1]
#         else:
#             print("Invalid choice. Please enter a number between 1 and {}.".format(len(options)))

# def main():
#     # Step 1: Ask user to choose the location/region
#     regions = dataset['Region'].unique()
#     region = get_user_input("Choose your location/region:", regions)

#     # Step 2: Ask user to choose the subcategory
#     subcategories = dataset['subcategories'].unique()
#     subcategory = get_user_input("Choose the subcategory:", subcategories)

#     # Step 3: Filter dataset based on the chosen subcategory
#     filtered_data = dataset[(dataset['Region'] == region) & (dataset['subcategories'] == subcategory)]

#     # Step 4: Show available subtypes for the chosen subcategory
#     subtypes = filtered_data['subtype'].unique()
#     subtype = get_user_input("Choose the subtype:", subtypes)

#     # Step 5: Recommend places based on the chosen location, subcategory, and subtype
#     recommended_places = recommend_places_with_similarity(filtered_data, region, subcategory)
#     print("\nRecommended Places:")
#     print(recommended_places)

# if __name__ == "__main__":
#     main()

Choose your location/region:
1. North Goa District
2. Jodhpur District
3. Jaipur District
4. Ajmer District
5. Ujjain District
6. Udaipur District
7. Mumbai
8. Pune District
9. Agra District
10. New Delhi
11. South Goa District
12. Thane District
13. Mahipalpur
14. None
15. Chennai District
16. Bundi District
17. Bangalore District
18. Gurgaon District
19. Dehradun District
20. Visakhapatnam District
21. Varanasi District
22. Kottayam District
23. Vikarabad District
24. Surat District
25. Kangra District
26. Gautam Buddha Nagar District
27. Nainital District
28. Raigad District
29. Kullu District
30. Ranchi District
31. Alwar District
32. Khurda District
33. Bhopal District
34. Kota District
35. Tumkur District
36. Kozhikode District
37. Chittoor District
38. Palghar  District
39. Udupi District
40. Thiruvananthapuram District
41. Tiruvannamalai District
42. Dindigul District
43. Faridabad District
44. Kalaburagi District
45. Lucknow District
46. Howrah District
47. Salem District
48. Patna District
49. West Midnapore District
50. Ahmedabad District
51. Mehsana District
52. Palakkad District
53. Kodagu (Coorg)
54. Idukki District
55. East Midnapore District
56. Bilaspur District
57. Wayanad District
58. East Godavari District
59. Sawai Madhopur District
60. Kanchipuram District
61. Bellary District
62. Sambalpur District
63. Pathanamthitta District
64. Gaya District
65. Jammu
66. Kanpur Nagar District
67. Panchkula District
68. Pauri Garhwal District
69. Kollam District
70. Uttara Kannada District
71. Ramanagara District
72. Solan District
73. Puri District
74. Cuddalore District
75. Mathura District
76. Agar Malwa District
77. Jaisalmer District
78. Navi Mumbai
79. Raipur District
80. Nellore District
81. Hassan District
82. Baghpat District
83. Gwalior District
84. Tiruchirappalli District
85. North Sikkim
86. Ramanathapuram District
87. Vellore District
88. Malappuram District
89. Hyderabad District
90. Bhavnagar District
91. Kashmir
92. Nashik District
93. Coimbatore District
94. Chikkaballapura District
95. Junagadh District
96. Chhatarpur District
97. Mohali District
98. Dangs District
99. Balasore District
100. Ratnagiri District
101. Satara District
102. Nagpur District
103. Amravati District
104. Valsad District
105. Bharuch District
106. Ernakulam District
107. Bikaner District
108. Ghaziabad District
109. Buldhana District
110. Dakshina Kannada District
111. Chamarajanagar District
112. Jamnagar District
113. Solapur District
114. Mandi District
115. Chikkamagaluru District
116. Shimla District
117. Kasaragod District
118. Thrissur District
119. Patialar District
120. Tiruppur District
121. Sindhudurg District
122. Krishnagiri District
123. The Nilgiris District
124. Haridwar District
125. Dhanbad District
126. Anand District
127. South Andaman Island
128. Gandhinagar District
129. Darjeeling District
130. Kanyakumari District
131. Purulia District
132. Tirunelveli District
133. Meerut District
134. Bijapur District
135. Bathindar District
136. Diu District
137. Mandya District
138. Sirohi District
139. Ahmednagar District
140. Kalimpong District
141. Kolar District
142. Daman
143. Ganjam District
144. Tawang District
145. Sivaganga District
146. Hoshangabad District
147. Kolkata District
148. Erode District
149. Pondicherry
150. Adilabad District
151. Kadapa District
152. Diveagar
153. Kannur District
154. Chitradurga District
155. Alappuzha District
156. Chamba District
157. Guntur District
158. Shimoga District
159. Cuttack District
160. Jalpaiguri District
161. Jabalpur District
162. Bardhaman District
163. Porbandar District
164. Jhansi
165. Anuppur District
166. Bareilly District
167. Vadodara District
168. West Jaintia Hills District
169. Jalgaon District
170. Rajkot District
171. Rudraprayag District
172. Kutch District
173. Nagapattinam District
174. West Tripura District
175. Viluppuram District
176. Mirzapur District
177. Imphal West District
178. Kurnool District
179. Sabarkantha District
180. Silvassa
181. Sonipat District
182. Jhajjar District
183. Nalanda District
184. Murshidabad District
185. Vizianagaram District
186. Bhadradri Kothagudem District
187. Kamrup Metropolitan District
188. Sangli District
189. Kurukshetra District
190. Bastar District
191. Dharmapuri District
192. Deoghar District

Choose the subcategory:
1. Zoos & Aquariums, Water & Amusement Parks, Fun & Games, Nature & Parks
2. Sights & Landmarks
3. Spas & Wellness
4. Fun & Games
5. Shopping
6. Nature & Parks
7. Shopping, Museums
8. Water & Amusement Parks
9. Sights & Landmarks, Nature & Parks
10. Food & Drink, Classes & Workshops
11. Food & Drink, Classes & Workshops, Other
12. Tours, Boat Tours & Water Sports, Outdoor Activities
13. Zoos & Aquariums, Nature & Parks, Outdoor Activities
14. Nature & Parks, Outdoor Activities
15. Museums
16. Sights & Landmarks, Outdoor Activities
17. Sights & Landmarks, Nature & Parks, Outdoor Activities
18. Events
19. Tours, Boat Tours & Water Sports, Transportation, Outdoor Activities
20. Casinos & Gambling, Fun & Games
21. Tours
22. Zoos & Aquariums, Water & Amusement Parks, Nature & Parks, Outdoor Activities
23. Sights & Landmarks, Museums
24. Museums, Water & Amusement Parks
25. Traveler Resources
26. Museums, Traveler Resources
27. Concerts & Shows
28. Museums, Nature & Parks
29. Fun & Games, Nature & Parks
30. Food & Drink
31. Transportation
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:
Invalid choice. Please enter a number between 1 and 0.
Choose the subtype:

In [66]:
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.feature_extraction.text import TfidfVectorizer

# def calculate_recommendation_score(row):
#     # Calculate recommendation score based on the number of reviews
#     return row['numberOfReviews'] /row['rawRanking']

# def recommend_places_with_similarity(dataset, region, subcategory, subtype):
#     # Step 1: Filter dataset by region, subcategory, and subtype
#     filtered_data = dataset[(dataset['Region'] == region) & 
#                             (dataset['subcategories'] == subcategory) & 
#                             (dataset['subtype'] == subtype)]

#     if filtered_data.empty:
#         return "No recommendations found for the selected region, subcategory, and subtype."

#     # Step 2: Calculate recommendation score based on number of reviews
#     filtered_data['recommendation_score'] = filtered_data.apply(calculate_recommendation_score, axis=1)

#     # Step 3: Vectorize the subcategory, subtype, and combined features
#     vectorizer = TfidfVectorizer()
#     subcategory_subtype_matrix = vectorizer.fit_transform(filtered_data['subcategories'] + ' ' + filtered_data['subtype'])

#     # Step 4: Calculate cosine similarity
#     similarity_matrix = cosine_similarity(subcategory_subtype_matrix, subcategory_subtype_matrix)

#     # Step 5: Get indices of places in descending order of similarity
#     sim_scores = list(enumerate(similarity_matrix[-1]))
#     sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
#     sim_scores = sim_scores[0:]  # Exclude the place itself

#     # Step 6: Get top recommendations based on similarity and recommendation score
#     top_indices = [x[0] for x in sim_scores]
#     top_recommendations = filtered_data.iloc[top_indices].sort_values(by=['recommendation_score'], ascending=False)

#     return top_recommendations[['name', 'rating', 'numberOfReviews', 'recommendation_score']]

# # Example usage:
# # Assuming dataset is your loaded DataFrame

In [74]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

def calculate_recommendation_score(row):
    # Calculate recommendation score based on the number of reviews
    return row['numberOfReviews'] /row['rawRanking']

def recommend_places_with_similarity(dataset, region, subcategory, subtype=None):
    # Step 1: Filter dataset by region and subcategory
    if subtype:
        filtered_data = dataset[(dataset['Region'] == region) & 
                                (dataset['subcategories'] == subcategory) & 
                                (dataset['subtype'] == subtype)]
    else:
        filtered_data = dataset[(dataset['Region'] == region) & 
                                (dataset['subcategories'] == subcategory)]

    if filtered_data.empty:
        return "No recommendations found for the selected region and subcategory."

    # Step 2: Calculate recommendation score based on number of reviews
    filtered_data['recommendation_score'] = filtered_data.apply(calculate_recommendation_score, axis=1)

    # Step 3: Vectorize the subcategory, subtype, and combined features
    vectorizer = TfidfVectorizer()
    if subtype:
        feature_text = filtered_data['subcategories'] + ' ' + filtered_data['subtype'] 
    else:
        feature_text = filtered_data['subcategories']
    feature_matrix = vectorizer.fit_transform(feature_text)

    # Step 4: Calculate cosine similarity
    similarity_matrix = cosine_similarity(feature_matrix, feature_matrix)

    # Step 5: Get indices of places in descending order of similarity
    sim_scores = list(enumerate(similarity_matrix[-1]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[0:]  # Exclude the place itself

    # Step 6: Get top recommendations based on similarity and recommendation score
    top_indices = [x[0] for x in sim_scores]
    top_recommendations = filtered_data.iloc[top_indices].sort_values(by=['recommendation_score'], ascending=False)

    return top_recommendations[['name', 'rating', 'numberOfReviews', 'recommendation_score']]

In [76]:
subtype = 'Water Parks'
region = 'Pune District'
subcategory = 'Water & Amusement Parks'
recommended_places = recommend_places_with_similarity(df, region, subcategory,subtype)
print(recommended_places)

                                      name  rating  numberOfReviews  \
324  Wet N Joy Water Park & Amusement Park     4.0              200

     recommendation_score
324             65.391495

C:\Users\DEVAVRAT\AppData\Local\Temp\ipykernel_18868\2533438768.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['recommendation_score'] = filtered_data.apply(calculate_recommendation_score, axis=1)

In [78]:
region = 'Jaipur District'
subcategory = 'Sights & Landmarks'
recommended_places = recommend_places_with_similarity(df, region, subcategory,subtype=None)
print(recommended_places)

                                   name  rating  numberOfReviews  \
15                         Amber Palace     4.5            18542
55                            Jal Mahal     4.0             3932
59                        Monkey Temple     4.0             1959
253                 Govind Devji Temple     4.5              709
95                       Galtaji Temple     4.0              378
159                 Royal Gaitor Tumbas     4.5              335
62   Khole Ke Hanuman JI Temple, Jaipur     4.5              269
240                Gatore Ki Chhatriyan     4.5               92
147                        Patrika Gate     4.5               84

     recommendation_score
15            3708.400000
55            1160.104874
59             559.830522
253            170.659909
95             117.465928
159             85.363957
62              75.253954
240             26.617689
147             23.019665

C:\Users\DEVAVRAT\AppData\Local\Temp\ipykernel_18868\2533438768.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['recommendation_score'] = filtered_data.apply(calculate_recommendation_score, axis=1)